#!/bin/bash

IRIT_RST_DT=$HOME/irit-rst-dt
cd "$IRIT_RST_DT"

mkdir -p OLD-LOGS
mv irit-rst-dt-evaluate-*.out OLD-LOGS

EVALUATE_FLAGS=("$@")
#EVALUATE_FLAGS=(--resume)
cd "$IRIT_RST_DT"
if [ ! -e "$IRIT_RST_DT"/cluster/env ]; then
    echo >&2 "Please set up your cluster/env script"
    echo >&2 "(copy from example and edit)"
    exit 1
fi


function j_sbatch {
    sbatch "$@" | sed -e 's/Submitted batch job //'
}

function mk_deps {
    for job in "$@"; do
       dep_str="${dep_str+$dep_str:}$job"
    done
    echo "${dep_str+afterok:}$dep_str"
}

set -e
source "$IRIT_RST_DT/cluster/env"
# create the evaluation folder
sjobs+=($(j_sbatch "$IRIT_RST_DT"/cluster/evaluate.script --start "${EVALUATE_FLAGS[@]}"))
sjob_str=$(mk_deps "${sjobs[@]}")

# generate the global model
# (only needed for reporting discriminating features)
# we launch this first only because it's very slow
# so we might as well start working on it early on
jobs+=($(j_sbatch --dependency="$sjob_str"\
    "$IRIT_RST_DT"/cluster/evaluate.script --combined-models "${EVALUATE_FLAGS[@]}"))
# request a job for each fold
jobs+=($(j_sbatch --dependency="$sjob_str"\
    "$IRIT_RST_DT"/cluster/evaluate.script --folds 0 1 "${EVALUATE_FLAGS[@]}"))
jobs+=($(j_sbatch --dependency="$sjob_str"\
    "$IRIT_RST_DT"/cluster/evaluate.script --folds 2 3 "${EVALUATE_FLAGS[@]}"))
jobs+=($(j_sbatch --dependency="$sjob_str"\
    "$IRIT_RST_DT"/cluster/evaluate.script --folds 4 5 "${EVALUATE_FLAGS[@]}"))
jobs+=($(j_sbatch --dependency="$sjob_str"\
    "$IRIT_RST_DT"/cluster/evaluate.script --folds 6 7 "${EVALUATE_FLAGS[@]}"))
jobs+=($(j_sbatch --dependency="$sjob_str"\
    "$IRIT_RST_DT"/cluster/evaluate.script --folds 8 9 "${EVALUATE_FLAGS[@]}"))
# generate the report when all folds are done
job_str=$(mk_deps "${jobs[@]}")
sbatch --dependency="$job_str" "$IRIT_RST_DT"/cluster/report.script
