#!/bin/bash

IRIT_RST_DT=$HOME/irit-rst-dt
cd "$IRIT_RST_DT"

mkdir -p OLD-LOGS
mv irit-rst-dt-evaluate-*.out OLD-LOGS

EVALUATE_FLAGS=("$@")
#EVALUATE_FLAGS=(--resume)
cd "$IRIT_RST_DT"
if [ ! -e "$IRIT_RST_DT"/cluster/env ]; then
    echo >&2 "Please set up your cluster/env script"
    echo >&2 "(copy from example and edit)"
    exit 1
fi


set -e
source "$IRIT_RST_DT/cluster/env"
# create the evaluation folder
sjobs+=($(sbatch "$IRIT_RST_DT"/cluster/evaluate.script --start "${EVALUATE_FLAGS[@]}" |\
         sed -e 's/Submitted batch job //'))
for job in "${sjobs[@]}"; do
   sjob_str="${sjob_str+$sjob_str,}afterok:$job"
done

# generate the global model
# (only needed for reporting discriminating features)
# we launch this first only because it's very slow
# so we might as well start working on it early on
jobs+=($(sbatch --dependency="$sjob_str"\
         "$IRIT_RST_DT"/cluster/evaluate.script --combined-models "${EVALUATE_FLAGS[@]}" |\
         sed -e 's/Submitted batch job //'))
# request a job for each fold
jobs+=($(sbatch --dependency="$sjob_str"\
            "$IRIT_RST_DT"/cluster/evaluate.script --folds 0 1 2 "${EVALUATE_FLAGS[@]}" |\
            sed -e 's/Submitted batch job //'))
jobs+=($(sbatch --dependency="$sjob_str"\
            "$IRIT_RST_DT"/cluster/evaluate.script --folds 3 4 5 "${EVALUATE_FLAGS[@]}" |\
            sed -e 's/Submitted batch job //'))
jobs+=($(sbatch --dependency="$sjob_str"\
            "$IRIT_RST_DT"/cluster/evaluate.script --folds 6 7 "${EVALUATE_FLAGS[@]}" |\
            sed -e 's/Submitted batch job //'))
jobs+=($(sbatch --dependency="$sjob_str"\
            "$IRIT_RST_DT"/cluster/evaluate.script --folds 8 9 "${EVALUATE_FLAGS[@]}" |\
            sed -e 's/Submitted batch job //'))


for job in "${jobs[@]}"; do
   job_str="${job_str+$job_str,}afterok:$job"
done
# generate the report when all folds are done
sbatch --dependency="$job_str" "$IRIT_RST_DT"/cluster/report.script
