#!/usr/bin/env python

'''
attelo command line interface

(merely dispatches to subcommands)
'''

import argparse

from attelo.cmd import SUBCOMMANDS


def main():
    "set up args and launch the appropriate subcommand"
    arg_parser = argparse.ArgumentParser(description='Attelo '
                                         'Discourse Parsing Toolkit')
    subparsers = arg_parser.add_subparsers(help='sub-command help')

    for module in SUBCOMMANDS:
        if 'NAME' in module.__dict__:
            # pylint: disable=no-member
            module_name = module.NAME
            # pylint: enable=no-member
        else:
            module_name = module.__name__.split('.')[-1]
        subparser = subparsers.add_parser(module_name,
                                          help=module.__doc__)
        module.config_argparser(subparser)

    args = arg_parser.parse_args()
    args.func(args)

main()
